[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "build"
  functions = "netlify/functions"

# Configurazioni per le funzioni serverless
[functions]
  # Configurazioni globali per tutte le funzioni
  external_node_modules = ["node-fetch"]

# Configurazioni per l'ambiente di produzione
[context.production]
  [context.production.functions]
    external_node_modules = ["node-fetch"]

# Configurazioni per l'ambiente di sviluppo
[context.deploy-preview]
  [context.deploy-preview.functions]
    external_node_modules = ["node-fetch"] 